### ISSUE TITLE
【Refactor】增加独立的 logger 包，避免打印日志时都引用 dtmcli/dtmimp 包

### ISSUE THREAD

**Issue by lsytj0413** [dtm-labs/dtm#105]

**Comment by yedf2** [comment]
这个会在近期加入。

因为现在redis存储引擎的性能很高，接下来会对日志分级重构，正好也把这块重构一下。

你近期提了很多好的意见，方便加个微信吗？

**Comment by lsytj0413** [comment]
> 这个会在近期加入。
> 
> 因为现在redis存储引擎的性能很高，接下来会对日志分级重构，正好也把这块重构一下。
> 
> 你近期提了很多好的意见，方便加个微信吗？

我直接微信联系你吧

**Comment by yedf2** [comment]
看看这个PR，任何想法我们可以继续讨论

**Comment by lsytj0413** [comment]
> 看看这个PR，任何想法我们可以继续讨论

我大致看了下：

- logger 包要不还是放在 dtm/logger 或者 dtm/utils/logger 下？感觉放在 dtmcli 下不是很合适
- 有些函数比较少见，例如 FatalIf

**Comment by yedf2** [comment]
因为使用dtm的用户，在SDK层，最好不引入dtm，所以我把dtm-labs/dtm/dtmcli单独复制到dtm-labs/dtmcli仓库，单独发布。这种情况下logger就不太适合放在dtm下面

因为if log.fatal的代码会比较多，所以弄了个fatalif
