### ISSUE TITLE
是否支持ent ， 有计划支持吗？？？？？

### ISSUE THREAD

**Issue by shuqingzai** [dtm-labs/dtm#112]
是否支持 [ent](https://github.com/ent/ent) ?? 是否有计划支持 ？？

**Comment by yedf2** [comment]
目前dtm支持go的标准sql.DB和sql.Tx，之前粗略看了一下ent，没有找到ent和标准的sql.DB/Tx如何互操作的。

如果ent提供了这方面的能力，那么就能够在dtm里面使用。

如果ent没有提供这方面的能力，那么需要在ent那边添加支持才行。dtm支持xorm的方式是，我跟xorm的作者沟通，发了一个PR完成的支持。有可能ent也需要熟悉ent的人帮忙对接和补充文档，不知道您是否有兴趣

**Comment by shuqingzai** [comment]
ent 可以整合 sql.DB ，你所说的互操作指哪部分？ 参考 [整合sql.DB](https://entgo.io/zh/docs/sql-integration)  https://github.com/ent/ent/blob/899e9f0e50ba6dbfb4e35dc1ea1bb0b319b66477/dialect/sql/driver.go

**Comment by yedf2** [comment]
OK，有这个互操作的支持，那么dtm就能够无缝支持ent。如果你在实际中使用，遇见问题，我可以解答。

如果您对接成功了，那么您把相关的代码片段给我，我补充到这个文档里 https://dtm.pub/summary/db.html
