### ISSUE TITLE
新人贡献上手任务

### ISSUE THREAD

**Issue by yedf2** [dtm-labs/dtm#114]
这里的任务，主要是为了帮助新人熟悉dtm的贡献PR流程，如果您已经是一个熟练的开源贡献者，请参考 #93

这里的任务比较多，您仅需要上手做一到两个，熟悉流程之后，就可以去做更有挑战的任务，参考 #93

- dtmsvr/storage下的文件，可以加上开源版权注释，每个文件的一行作为一个任务，发一个PR
- dtmcli/dtmimp/trans_xa_base.go中的中文注释翻译成英文注释，每行注释翻译，作为一个任务，发一个PR
- dtmcli/tcc.go中的注释翻译，同上
- 运行make之后，修复其中一个golangci-lint检测出来的问题，发一个PR

**Comment by lsytj0413** [comment]
加上修复 lint 的错误吧，现在代码里面的 lint 错误挺多的

**Comment by yedf2** [comment]
> 加上修复 lint 的错误吧，现在代码里面的 lint 错误挺多的

Done

**Comment by wondar-chan** [comment]
dev分支的dmtsrv下面没有storage目录了，是不是改为中文注释改成英文注释的方式来熟悉pr了呢
