### ISSUE TITLE
docker 使用 环境变量无效，默认连接还是 bolt 

### ISSUE THREAD

**Issue by costa92** [dtm-labs/dtm#135]
执行docker 运行命令：

`
sudo docker run -d --name dtm -p 36789:36789 -p 36790:36790 -e DRIVER_STORE_HOST='127.0.0.1' -e DRIVER_STORE_USER='root' -e DRIVER_STORE_PASSWORD='123456' -e DRIVER_STORE_PORT="3306" -e DRIVER_STORE_DRIVER="mysql"  yedf/dtm:latest
`
环境变量参考的是：
![image](https://user-images.githubusercontent.com/10903903/147471216-a915b607-ccec-4aff-90d0-7dd354e6dc02.png)

进入docker 中查看 :
![image](https://user-images.githubusercontent.com/10903903/147471312-20387822-31af-402a-93f2-e67065fe02ed.png)

连接的数据还是bolt ，请求是配置环境变量有问题，还是需要其他的配置消息

**Comment by yedf2** [comment]
抱歉，文档中的环境变量名错了，文档已更新，您可以看一下最新的文档页面。

另外v1.7.5修复了一个配置拼写错误，因此也请您更新一下最新的docker image

**Comment by yedf2** [comment]
昨天发布流水线出了问题，现在1.7.5的docker image已经好了

**Comment by costa92** [comment]
![image](https://user-images.githubusercontent.com/10903903/147517720-9fdb38dd-2a17-4b9d-b939-2759e3ea63ab.png)

`
docker run --name dtm -p 36789:36789 -p 36790:36790 -e DB_HOST='localhost' DB_USER='root' DB_PASSWORD='' dtm-labs/dtm:latest
`

dtm-labs/dtm:latest 在hub 仓库中没有这个镜像，不过可能是你们本地仓库吧

**Comment by yedf2** [comment]
文档已更新
这个问题是周末github组织从yedf/dtm改名为dtm-labs/dtm导致的

您可以用这个命令，将dtm服务器跑起来：
docker run --name dtm -p 36789:36789 -p 36790:36790 -e STORE_DRIVER='mysql' -e STORE_HOST='localhost' -e STORE_USER='root' -e STORE_PASSWORD='' -e STORE_PORT='3306' yedf/dtm:1.7.5

**Comment by costa92** [comment]
已经解决了，你们那个k8s 文档的环境变量也需要更新一下

**Comment by yedf2** [comment]
已更新
