### ISSUE TITLE
saga模式下，如何在不同的微服务之间传递结果？

### ISSUE THREAD

**Issue by csimplestring** [dtm-labs/dtm#137]
您好，现在在使用dtm的saga模式，有三个微服务A B C。B的输入依靠A的输出，C的输入依靠B的输出。dtm是否提供一个类似于context的机制用来在不同的action，compensate之间传递数据？

**Comment by yedf2** [comment]
这是一个好问题，几句话说不完，方便加微信yedf2008讨论一下吗？

**Comment by csimplestring** [comment]
好的

**Comment by csimplestring** [comment]
结论：
- 必须首先确保每个微服提供了幂等性
- 每个微服务可以提供一个结果的查询接口
