### ISSUE TITLE
如何使用rest风格的api作为action或compensate

### ISSUE THREAD

**Issue by jzdwk** [dtm-labs/dtm#140]
您好，有个小白问题，如果各服务组件都使用rest api，比如增加资源接口类似 POST /resource  删除资源接口 DELETE /resource/{name}，其他服务类似，且接口不可更改。那么如何使用比如saga呢？（看示例中的action与compensate使用path区分）

**Comment by yedf2** [comment]
这样的话，你可以做一层网关，定制成功和错误的结果。或者简单的说，你用你熟悉的语言，写新的符合dtm规范的接口，内部请求已有的接口，然后让dtm调用你的新接口

**Comment by jzdwk** [comment]
> 这样的话，你可以做一层网关，定制成功和错误的结果。或者简单的说，你用你熟悉的语言，写新的符合dtm规范的接口，内部请求已有的接口，然后让dtm调用你的新接口

如果引入网关去做一层封装，如何保证 网关->服务A 这条路径(同样是http)的请求是一定成功的，对于dtm，它只依赖网关的结果做commit or rollback，但并不能确定服务A是否消费成功，我理解这样就套环了。

**Comment by yedf2** [comment]
不会的，网关返回成功，那么就是确定的成功了。网关返回失败就是确定失败了，网关返回500则会重试。
但是业务层面，你需要保证你原有的服务幂等，自己妥善处理了悬挂空补偿

**Comment by csimplestring** [comment]
您好，我最近也在做类似的项目。现在dtm判断成功/失败是根据response.String()中是否包含“Success”, "Failure"来判断，第三方api通常不可更改。dtm能否支持直接使用返回结果的http status code来判断？比如设计一个status code到success/failure 的映射：

```Go

successCodes := [200, 201]
failureCodes := [400, 401, 403, 404, 500]
saga := dtmcli.NewSaga(dtmutil.DefaultHttpServer, dtmcli.MustGenGid(dtmutil.DefaultHttpServer)).
			Add(busi.Busi+"/TransOut", busi.Busi+"/TransOutRevert", req, successCodes, failureCodes).
			Add(busi.Busi+"/TransIn", busi.Busi+"/TransInRevert", req, successCodes, failureCodes)
```

这个功能可以省去新添加一个网关，而且每个分支的判断也独立，使用起来也方便一些。不知道这个建议是否可行？

**Comment by yedf2** [comment]
这个方案有考虑过，failureCodes一般不会选定你给的这几个，因为含义和failure不太一致。我考虑的Code是StatusConflict

https://www.cnblogs.com/rsapaper/p/9304192.html

因为SUCCESS、FAILURE是成熟的，已经在生产上验证过的，所以不会有大的问题，也不是很着急要改用HTTP的Code

现在新加了ONGOING之后，又会有一些要考虑的地方，后续可能会在社区里面讨论是否以特定的Code最为FAILURE和ONGOING

**Comment by csimplestring** [comment]
感谢回复！这个例子的status code确实不太标准，现实中我总遇到大量不规范的rest API，有些api用500代替4xx，有些只有200等等，因此希望能允许用户给每一个子事务灵活定义哪些code表示成功，哪些code表示失败，哪些code表示ongoing。

**Comment by yedf2** [comment]
收到，这个后续考虑

**Comment by yedf2** [comment]
v1.10.0已完成新的status code，详情参考 https://dtm.pub/practice/arch.html#proto
