### ISSUE TITLE
请教：saga模式下，何时需要使用子事务屏障？

### ISSUE THREAD

**Issue by csimplestring** [dtm-labs/dtm#144]
大佬，你好。
根据我的理解，如果我不使用并行的saga，那么就不需要使用子事务屏障了，因为不会有乱序的情况发生，saga中的每一个子事务都是一步一步来执行的。不知道我的理解是否正确？

**Comment by yedf2** [comment]
满足以下条件的saga，可以不需要使用子事务屏障：

1. 未使用并行saga
2. 未使用超时
3. 子事务的action和compensate已经是幂等的

**Comment by csimplestring** [comment]
那如果saga中调用了一个第三方api但不能保证幂等，那么子事务屏障就能解决这个问题吗？

**Comment by yedf2** [comment]
您看一下子事务屏障的文档，里面详细介绍了原理与适用的场景
