### ISSUE TITLE
SAGA模式怎么确保逆向操作一定成功？

### ISSUE THREAD

**Issue by panyox** [dtm-labs/dtm#18]

**Comment by yedf2** [comment]
按照saga模式的协议，逆向是不允许失败的，如果应用程序返回失败，那么就是出现bug了。
dtm会不断重试，直到saga的逆向返回成功。
为了避免程序bug导致逆向一直不成功，建议开发者对全局事务表进行监控，发现重试超过3次的事务，发出报警，由运维人员找开发手动处理

**Comment by XIELongDragon** [comment]
> 按照saga模式的协议，逆向是不允许失败的，如果应用程序返回失败，那么就是出现bug了。
> dtm会不断重试，直到saga的逆向返回成功。
> 为了避免程序bug导致逆向一直不成功，建议开发者对全局事务表进行监控，发现重试超过3次的事务，发出报警，由运维人员找开发手动处理

如果这样，那建议DTM服务器提供metric接口，便于接入grafana等进行自动监控和报警

**Comment by yedf2** [comment]
> > 按照saga模式的协议，逆向是不允许失败的，如果应用程序返回失败，那么就是出现bug了。
> > dtm会不断重试，直到saga的逆向返回成功。
> > 为了避免程序bug导致逆向一直不成功，建议开发者对全局事务表进行监控，发现重试超过3次的事务，发出报警，由运维人员找开发手动处理
> 
> 如果这样，那建议DTM服务器提供metric接口，便于接入Prometheus, grafana等进行自动监控和报警

@XIELongDragon  已添加Prometheus监控，在端口8889下的/api/metrics
