### ISSUE TITLE
关于子事务屏障问题

### ISSUE THREAD

**Issue by ZZhongge** [dtm-labs/dtm#181]
看介绍中需要写入数据库，想问一下这个是需要和busiCall放在同一个事务当中吗，那整个的事务提交是不是都交由子事务屏障来处理。如果不在事务当中，那么是否没法处理try和cancel依次经过屏障后，发生乱序，需要业务自己来保证。

**Comment by yedf2** [comment]
1. ”看介绍中需要写入数据库，想问一下这个是需要和busiCall放在同一个事务当中吗“ 需要在同一个事务，详情参考子事务屏障的原理介绍
2. ”如果不在事务当中，那么是否没法处理try和cancel依次经过屏障后，发生乱序，需要业务自己来保证。“ 是的

**Comment by ZZhongge** [comment]
我是看了原理，这个同一个事务是由子事务屏障来做提交吗，还是我自己在屏障前后做事务的开启和提交。是否由屏障来处理比较好。

**Comment by yedf2** [comment]
你看看dtm-examples里面CallWithDB的例子，事务的开启和提交/回滚，都是由屏障处理的

**Comment by WineChord** [comment]
所以其实相当于这个 busiCall 必须入参是一个 `*sql.Tx`，也就是必须是 SQL 语句，而不能是一个 rpc call
