### ISSUE TITLE
error spell on dtmsvr/config/config.go

### ISSUE THREAD

**Issue by authurguo** [dtm-labs/dtm#182]
dtmsvr/config/config.go 代码文件中的 `TransBranchOpTable` 的 yaml 配置名为 `BranchTransOpTable`。

> TransBranchOpTable string `yaml:"BranchTransOpTable" default:"dtm.trans_branch_op"`

但是，conf.sample.yml 中的示例配置为 `TransBranchOpTable`。

按照，前后文的行文习惯分析，config.go 中应该 yaml 配置名应该是错误拼写，需要修改为 `TransBranchOpTable`。

**Comment by yedf2** [comment]
已合并，可能因为你的提交邮箱，不在你的github帐号里面，导致contributor里面没有出现你，你帮忙看看你的邮箱设置，加一下你的提交邮箱？

**Comment by authurguo** [comment]
> 已合并，可能因为你的提交邮箱，不在你的github帐号里面，导致contributor里面没有出现你，你帮忙看看你的邮箱设置，加一下你的提交邮箱？

我的邮箱是 authurg.io@outlook.com, 我把项目的邮箱设置更改一下，感谢～
