### ISSUE TITLE
Write log to file

### ISSUE THREAD

**Issue by tinattwang** [dtm-labs/dtm#185]
1. Config log file name by yaml
2. Support log rotate
3. Simultaneously output logs to console and file

**Comment by yedf2** [comment]
The added config seems to output to only file, not console and file.
I temporarily revert this PR, and will find out how to specify both console and file

**Comment by yedf2** [comment]
I suggest:
remove Log.Filename
change Output => Outputs "default:stderr"
user can specify additional file like this: 
outputs: stderr,/tmp/dtm.log,/tmp/dtm2.log

etcd config is similar

**Comment by yedf2** [comment]
I have refactored this pr, final version can be seen: 
`git diff 54ef71b..fe674db`

changes:
Log.Level => LogLevel.  compatible with old version
InitLog back. compatible with old version
multiple file supported when rotate enabled. file log is checked manually, but rotate not checked manually.
simplified error handling

**Comment by tinattwang** [comment]
have learned, extremely grateful
