### ISSUE TITLE
网络不通的时候也适用吗

### ISSUE THREAD

**Issue by a6965921** [dtm-labs/dtm#200]
网络不通的时候也适用吗
比方A   请求B数据库 减去100    请求C数据库加上100 但是这个时候A和B C网络都不好了  所以C失败了  B会撤回码

**Comment by yedf2** [comment]
dtm 会管理好网络不通的情况。
你说的场景，dtm可以支持，你需要使用dtm做相关的试验，碰到具体的问题，讨论相关方案。

C网络失败，SAGA 不回滚而会重试，TCC 则会回滚。

一个服务访问两个数据库，需要用两个子事务屏障进行处理
