### ISSUE TITLE
Msg支持延迟消息

### ISSUE THREAD

**Issue by yedf2** [dtm-labs/dtm#208]
Msg添加选项 Delay，含义为延迟多久执行。当这个选项非0时，那么Submit之后，不立即调用分支，而是设定NextCronTime之后立即返回

**Comment by xyctruth** [comment]
Delay 单位应该是什么，还有一个问题就是会不会有大量的 Delay 请求导致Cron轮训不过来，导致时间的误差。

**Comment by yedf2** [comment]
Delay的单位是秒

你提到的这个轮询不过来，导致时间误差，是可能存在的。即使是消息队列中的延时消息，也一样有这样的问题，即使一个应用内部的sleep也有这个问题，所以应用期待的是，api被调用，被执行时，延时大于等于这个时间，而不应当期待等于这个时间

**Comment by xyctruth** [comment]
> Delay的单位是秒
> 
> 你提到的这个轮询不过来，导致时间误差，是可能存在的。即使是消息队列中的延时消息，也一样有这样的问题，即使一个应用内部的sleep也有这个问题，所以应用期待的是，api被调用，被执行时，延时大于等于这个时间，而不应当期待等于这个时间

ok , Delay 需要存储到TransGlobalStore吗？方便之后追溯？

**Comment by yedf2** [comment]
Delay就作为TransOption中的一个字段，保存到TransGlobalStore
空间占用不大，这样的设计就OK

**Comment by yedf2** [comment]
不是前面说的TransOption，而是类似Saga中的CustomData，这个选项只有Msg会用，其他事务不需要

**Comment by xyctruth** [comment]
> 不是前面说的TransOption，而是类似Saga中的CustomData，这个选项只有Msg会用，其他事务不需要

ok, 指派给我吧，我下周可以开始这个问题。

**Comment by xyctruth** [comment]
@yedf2 

saga 是在 transSagaProcessor.ProcessOnce 处理CustomData。
msg 的 Delay 字段放在 CustomData 中的话，我也准备在 transMsgProcessor.ProcessOnce 中处理，去更新 `NextCronTime`后，并不去执行接下来的分支。
但现在 Store.TouchCronTime 提供的更新方法是传入 `nextCronInterval` 参数，然后在方法内计算 `NextCronTime`,如果我传入 `Delay`, 会影响`NextCronInterval`字段的初始值，导致失败后的重试退避时间也延长。
现在是否把 Store.TouchCronTime 参数改成接收  `nextCronInterval` ， `nextCronTime`? 

或者在 ` t.saveNew()` 之前处理，但在目前在 ` t.saveNew()`之前都是统一的方法。并没有 `saga`,`msg`,`tcc`,`xa`的多态方法。

**Comment by yedf2** [comment]
把 Store.TouchCronTime 参数改成接收 nextCronInterval ， nextCronTime ?
这种做法问题应该不大
