### ISSUE TITLE
一个事务分支的请求结果如何给到另一个事务分支

### ISSUE THREAD

**Issue by eclipsexml** [dtm-labs/dtm#211]
目前dtm 要求所有事务分支使用同一请求 那么例如一个saga 内 某一个事务分支的请求与其他不一样 或者来自于前序分支的执行结果 这时该如何处理

**Comment by eclipsexml** [comment]
目前我能想到的是通过共享缓存处理 还有其他方法吗

**Comment by eclipsexml** [comment]
或者请求里有个扩展字段

**Comment by yedf2** [comment]
每个分支的请求body是分别传递的，可以不同，只是例子为了简短，没有写成不同

其他分支的结果，如果要传递的话，那么可以选择各种手动的方法，例如再提供一个API查询，也可以共享缓存；也可以选择TCC模式，然后把confirm设置为空字符串

**Comment by eclipsexml** [comment]
改扩展字段 会传递前面事务分支处理的结果或者需要传递到下一请求的数据

**Comment by yedf2** [comment]
能否详细说一说你的方案，包括具体的过程，以及为什么比手动提供一个API更优？

**Comment by eclipsexml** [comment]
> 能否详细说一说你的方案，包括具体的过程，以及为什么比手动提供一个API更优？
