### ISSUE TITLE
子事务屏障技术的疑问

### ISSUE THREAD

**Issue by alvin-7** [dtm-labs/dtm#231]
1. 开启本地事务
2. 对于当前操作op(try|confirm|cancel)，insert ignore一条数据gid-branchid-op，如果插入不成功，提交事务返回成功（常见的幂等控制方法）
3. 如果当前操作是cancel，那么在insert ignore一条数据gid-branchid-try，如果插入成功（注意是成功），则提交事务返回成功
4. 调用屏障内的业务逻辑，如果业务返回成功，则提交事务返回成功；如果业务返回失败，则回滚事务返回失败
在此机制下，解决了乱序相关的问题

以上是 子事务屏障技术 的实现原理，我有以下疑问：
1. cancel的时候，为什么是insert成功 才代表事务返回成功呢？我理解的是，先cancel del这条gid-branchid-op，如果成功则事务成功；后续cancel的时候，无法del，所以保证了幂等
2. 如何保证此操作与事务的原子性呢。比如事务是扣除table表单行数据，这个insert是针对另外的表嘛？所以需要使用数据库的事务来保证这两个操作是原子性嘛？

以上是我的疑问，希望能够您宝贵时间下的解答，谢谢

**Comment by alvin-7** [comment]
补充以下，如果如我的理解的话，那我们在编写事务的时候，需要使用到数据库对应的事务写法。例如Mongodb，我们的操作需要带上事务session去操作，使得与dtm的session是同一个事务

**Comment by xyctruth** [comment]
cancel 时会插入两条屏障数据 try 与 cancel。


try 屏障插入成功，直接返回成功，不执行 cancel 业务函数。
try 屏障插入失败，执行 cancel 业务函数，返回成功。

当然这都是建立下 插入 cancel 屏障成功的基础上

**Comment by xyctruth** [comment]
> 补充以下，如果如我的理解的话，那我们在编写事务的时候，需要使用到数据库对应的事务写法。例如Mongodb，我们的操作需要带上事务session去操作，使得与dtm的session是同一个事务

这个是肯定的

**Comment by alvin-7** [comment]
> cancel 时会插入两条屏障数据 try 与 cancel。
> 
> try 屏障插入成功，直接返回成功，不执行 cancel 业务函数。 try 屏障插入失败，执行 cancel 业务函数，返回成功。
> 
> 当然这都是建立下 插入 cancel 屏障成功的基础上

谢谢解答，明白了，就是try成功，屏障就无法insert成功，所以需要执行cancel；否则屏障insert成功，代表try失败了，所以不需要执行cancel
