### ISSUE TITLE
子事务屏障实现的tcc

### ISSUE THREAD

**Issue by hehuilei** [dtm-labs/dtm#235]
1、https://github.com/dtm-labs/dtm-examples/blob/main/examples/http_tcc_barrier.go 例子是带事务屏障的吗？ 看代码好像并没有

2、子事务屏障的业务方法签名中带有sql.tx， 如果业务逻辑只是一个rpc的请求，这个db参数也可以不使用吧？
// BarrierBusiFunc type for busi func
type BarrierBusiFunc func(tx *sql.Tx) error

**Comment by yedf2** [comment]
1. 有呀，你看一下分支操作，里面有子事务屏障。运行时，也有相关的日志
2. 如果你的这个rpc请求自身已经做好了异常的处理，那么你直接调用就行了，子事务屏障都不需要。否则要理解一下子事务屏障的原理，然后用于你的业务
