### ISSUE TITLE
关于使用Postgres时，insert ignore语法不支持的问题

### ISSUE THREAD

**Issue by liuyu2018** [dtm-labs/dtm#236]
![image](https://user-images.githubusercontent.com/36878434/156129787-e21e1cc4-1475-494a-a57a-764c2956eccf.png)

我在使用postgres时，事务进行了回滚操作，但是postgres不支持insert ignore导致异常，我在文档里没看到相关的处理方法，请教下这个问题是由我们开发者自己处理绕过么？还是我遗漏了文档里的某些内容？

**Comment by xyctruth** [comment]
可以通过 `dtmcli.SetCurrentDBType(dtmcli.DBTypePostgres)` 来设置使用postgres

**Comment by liuyu2018** [comment]
谢谢大佬，我文档看漏了，下次一定注意

**Comment by xyctruth** [comment]
> 谢谢大佬，我文档看漏了，下次一定注意

没关系, 漏看到一些内容很正常，也有可能一些文档也缺少一些内容。
