### ISSUE TITLE
并发情况下原子加1问题

### ISSUE THREAD

**Issue by happyxhw** [dtm-labs/dtm#238]
![image](https://user-images.githubusercontent.com/44490504/156313000-2b9a8ada-0965-4a52-b024-19473d88b2eb.png)

NewSubBranchID() 貌似会并发调用，这种情况下：
`
读取 g.subBranchID 和
g.subBranchID = g.subBranchID + 1
`
是非原子的

**Comment by yedf2** [comment]
请问一下您这边是什么场景下，会并发创建分支？
