### ISSUE TITLE
支持无限重试gid强制终止

### ISSUE THREAD

**Issue by Rennbon** [dtm-labs/dtm#241]
因为线上环境会有一些特殊异常，如上线时路径配错了，请求了错误路径，这种不需要正常修复，也不能将错就错在错误的方案上做弥补，这类重试的gid强制关闭即可，可以从组织架构上走审批来确保不会出错。

**Comment by Rennbon** [comment]
目前可以通过手动修改数据库trans_global中的status伪failed关闭gid

**Comment by yedf2** [comment]
已支持
