### ISSUE TITLE
DTM Saga 重试报错 "Duplicate entry 'eKmjr6iu4qfLCf5ydoDTA-01-action-01' for key 'gid'")

### ISSUE THREAD

**Issue by sunxiang1** [dtm-labs/dtm#244]
基于Python DTM的示例，在余额小于转出余额时，报错，Saga会不断重试，并报错 "Duplicate entry 'eKmjr6iu4qfLCf5ydoDTA-01-action-01' for key 'gid'"

**Comment by yedf2** [comment]
请帮忙把详细的复现步骤给一下
