### ISSUE TITLE
关于mongo 支持程度的疑问

### ISSUE THREAD

**Issue by 309791679** [dtm-labs/dtm#245]
你好，我还没有使用这个项目，但是我有一些疑问
就我自己目前项目而言，使用的数据库架构是mongo+redis，所以就会牵涉到嵌套增删改查的问题，我大概了解了项目，是将所有的sql语句交由 "dtm项目内部处理，最终实现回滚"，但是我可能会涉及到多层嵌套修改的问题，不知道这个方面对于mongo数据库支持的怎么样

**Comment by 309791679** [comment]
我会用到 mongo 中的 【Aggregate语句】实现业务需求，但是没有看到文档中关于sql语句的适配情况

**Comment by 309791679** [comment]
https://github.com/dtm-labs/dtm/blob/main/conf.sample.yml ,并且在这个页面也没找到关于 mongo的配置文件

**Comment by yedf2** [comment]
不太清楚你说的嵌套修改是指什么，对于dtm来说，只是需要mongo的事务支持，保证子事务屏障的修改和业务修改在同一个事务
如果这个问题还不清晰，你可以把你的详细场景描述清楚，放在这里讨论，这样能够很快清晰

**Comment by yedf2** [comment]
目前暂未支持将事务进度存储到mongo中
