### ISSUE TITLE
conf.sample.yml配置缺了个冒号

### ISSUE THREAD

**Issue by guoyizhi** [dtm-labs/dtm#250]
启动会报错 fatal error: yaml: line 33: could not find expected ':'

**Comment by yedf2** [comment]
这个是示例文件，默认为空白文件，如果要用的话，去掉部分注释后，然后把配置文件指定为这个文件就可以

**Comment by guoyizhi** [comment]
理解的 只是示例配置文件中 32行位置缺少了一个":" 已经提交PR 您看下是否有必要





来自钉钉专属商务邮箱------------------------------------------------------------------
***@***.***>
日　期：2022年04月10日 11:19:01
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [dtm-labs/dtm] conf.sample.yml配置缺了个冒号 (Issue #250)

这个是示例文件，默认为空白文件，如果要用的话，去掉部分注释后，然后把配置文件指定为这个文件就可以

**Comment by yedf2** [comment]
感谢pr
