### ISSUE TITLE
docker env variable introduce？

### ISSUE THREAD

**Issue by Coneboy-k** [dtm-labs/dtm#260]
Thanks for the DTM project. Could you please provide a description of the Docker env variable?

```
      STORE_DRIVER: xxx
      STORE_HOST: xxx
      STORE_USER: xx
      STORE_PASSWORD: 'xxx'
      STORE_PORT: xxx
```

**Comment by xyctruth** [comment]
see: https://dtm.pub/deploy/base.html#dtm%E9%85%8D%E7%BD%AE
