### ISSUE TITLE
C# SDK中saga模式的疑问

### ISSUE THREAD

**Issue by jiankea** [dtm-labs/dtm#272]
官方demo中saga模式设置了 SetTimeoutToFail 后，提交分支操作若遇到dtm未知结果，saga状态由submitted 重试后置为 fail，分支状态却是prepared ，dtm并未调用补偿？
![image](https://user-images.githubusercontent.com/104048870/164146905-e9180fd7-2563-40c6-b7b9-35b2d39ad15b.png)
![image](https://user-images.githubusercontent.com/104048870/164146912-4633c110-0a34-4304-9a14-e26d1570cfa1.png)
![image](https://user-images.githubusercontent.com/104048870/164146928-874881f4-549a-4bf4-af35-68b9b9ea1825.png)
![image](https://user-images.githubusercontent.com/104048870/164146931-2aac4cb7-63aa-43c0-8ec9-6a49a200aefd.png)

**Comment by yedf2** [comment]
这个是dtm服务器的bug，已经修复，并且已经合并到main分支
