### ISSUE TITLE
Seeking advice for usage of dtm

### ISSUE THREAD

**Issue by SgtDaJim** [dtm-labs/dtm#277]
I build a service which connected to multiple MySQLs，and has a logic that will start an XA transaction on these dbs.
On the consideration of distributed transaction, should I set up the grpc server for the logic and  use DTM to control the XA transaction, or i just need to let my service to be the TM and control the XA transaction?

Looking forward to suggestions!

**Comment by yedf2** [comment]
In DTM, the cooperating model is the same as XA/OPEN DTP, and TM refers to DTM.

In order to use DTM as XA transaction manager, APP should provide a service for each XA transaction.

An example can be found here: d.dtm.pub/practice/xa.html

**Comment by SgtDaJim** [comment]
@yedf2 understood. but all my logic are in the same service... so i have to expose a grpc server in my service and program my service to call itself?

**Comment by yedf2** [comment]
Yes. It is the easiest way to implement XA transaction.

**Comment by SgtDaJim** [comment]
@yedf2 understood. I will have a try. thanks.

**Comment by SgtDaJim** [comment]
@yedf2 another question, i check the code of dtm about xa local transaction, find that the server side has to do sql.Open in every transaction. I think it will cause bad performance. It there any approach i can just pass a connection instead of the DBConf?
https://github.com/dtm-labs/dtm/blob/31bf7d9fad4d0b6a15b5573229053eda5603b745/dtmcli/dtmimp/trans_xa_base.go#L36

**Comment by yedf2** [comment]
Because the implementation of XA transaction in Mysql cannot xa_commit a transaction began in another connection if it is still alive, so dtm will create a new connection whenever to begin a xa_prepare.

As well known, XA performance is not high. If you want high performance, you may consider Saga or Tcc

**Comment by SgtDaJim** [comment]
> Because the implementation of XA transaction in Mysql cannot xa_commit a transaction began in another connection if it is still alive, so dtm will create a new connection whenever to begin a xa_prepare.

I am wondering, what if handling the connection like this:
```Go
// map[xid]*sql.Conn
var connMap = sync.Map{}
func HandleLocalTransaction(ctx context.Context, db *sql.DB, func (ctx context.Context, db *sql.DB, xa *dtmgrpc.XaGrpc) error {
    if phase 2{
         // get the Connection used in phase 1
         conn := connMap. LoadAndDelete(xid).(*sql.Conn)
         defer conn.Close()
         // ping here to check if the connection still alive
         err := conn.PingContext(ctx)
         if err != nil{
                // use *sql.DB to do phase 2
         }else{
                // use the connection to do phase 2
         }
    }
    // get a connection from pool
    conn := db.Conn()
    // phase 1
   // start
  // do something
   // end
   // prepare
   connMap.Stora(xid, conn)
}
```

> As well known, XA performance is not high. If you want high performance, you may consider Saga or Tcc

You are right. But we can still do more to improve the performance.

**Comment by yedf2** [comment]
If there is only one service instance, you implementation is OK. But in real applications, there are many service instance behind nginx or nginx-ingress, and report to dtm with an identical url. When dtm callback the url in phase 2, the requests are likely forwarded to a different service instance, make the implementation above not working.

**Comment by SgtDaJim** [comment]
Understood. Thanks.

**Comment by SgtDaJim** [comment]
@yedf2 can i call xa.CallBranch concorrently? like in different goroutine at the same time?

**Comment by yedf2** [comment]
No, currently not supported.
Maybe supported in the future.

**Comment by SgtDaJim** [comment]
I get a log from dtm:
----recovered panic http/grpc result should be specified as in:\nhttps://dtm.pub/summary/arch.html#http\nunkown result will be retried: rpc error: code = Internal desc = DB group  not found
what dose it mean? what should i do to handle it?

**Comment by yedf2** [comment]
I search the desc in google, but found nothing.

You should enable the debug log for dtm, and also log out all SQLs before executing it, and find out which sql is reporting error.

**Comment by yedf2** [comment]
@SgtDaJim is your problem solved? not active for 2 months, I would like to close it

**Comment by SgtDaJim** [comment]
@yedf2 problem solved. thanks.
