### ISSUE TITLE
dtm server数据库异常的问题

### ISSUE THREAD

**Issue by lzw621558** [dtm-labs/dtm#278]
![image](https://user-images.githubusercontent.com/31823210/164743761-427235f5-4dcd-46c6-a31c-bc63da04b8e4.png)
在今天中午十二点过后，服务所有的注册事务全都出现了如上图所示的异常情况，succeed在action之前就插入了，然后根据update time看发起时间又是succeed这一条在后，目前不清楚是由于什么原因导致的，本来应该更新branch_id为1的status，结果莫名其妙插入了一条数据，导致global事务查询状态失败，然后事务所有的注册事务全部阻塞。

**Comment by lzw621558** [comment]
![image](https://user-images.githubusercontent.com/31823210/164747825-905d0529-9739-441a-b01e-252d927bdea7.png)
看了一下好像是因为在更新时not matched然后直接向数据库插入了一条数据

**Comment by yedf2** [comment]
你看看为何更新数据库的时候，会导致branch_id和op这两个字段变成了空字符串，然后导致UpdateBranches变成了新插入数据

另外很奇怪的是，之前没有问题的，怎么突然某个时间之后就全部出问题了

**Comment by yedf2** [comment]
已经找到了出问题的时间点，那么就想一想这个时间点左右有什么变化，为什么会突然出问题了

**Comment by lzw621558** [comment]
> 已经找到了出问题的时间点，那么就想一想这个时间点左右有什么变化，为什么会突然出问题了

插了一下服务器在十二点之后比较卡，dtm镜像经常打印slow sql。很明显的就是在子事务成功时候调用了Gorm的upsert，时间要早于dtm注册branch的时间，（从图中可以看出，succeed这条数据的id要小于aciton这条数据的id，但是update_time要晚）

所以在用GORM的upsert时，根据AssignmentColumns的规则将列更新为新值？更新的时候只有status和finishtime字段，所以就create了一条空的数据

**Comment by lzw621558** [comment]
> > 已经找到了出问题的时间点，那么就想一想这个时间点左右有什么变化，为什么会突然出问题了
> 
> 插了一下服务器在十二点之后比较卡，dtm镜像经常打印slow sql。很明显的就是在子事务成功时候调用了Gorm的upsert，时间要早于dtm注册branch的时间，（从图中可以看出，succeed这条数据的id要小于aciton这条数据的id，但是update_time要晚）
> 
> 所以在用GORM的upsert时，根据AssignmentColumns的规则将列更新为新值？更新的时候只有status和finishtime字段，所以就create了一条空的数据

或者是由于req太大了，也可能是slow sql的原因之一。。。总之就是udpate branch的时候出错了

**Comment by yedf2** [comment]
加我微信 yedf2008 吧，有一些想法需要确认，issue里面沟通效率太低
