### ISSUE TITLE
Request: Provide docker-compose file for running tests.

### ISSUE THREAD

**Issue by zsc347** [dtm-labs/dtm#280]
Currently tests can not run successfully unless local MySQL service started.

Request: provide docker-compose file to start up redis, mysql service for running tests.

**Comment by yedf2** [comment]
it is provided here: helper/compose.store.yml

develop document is here: http://d.dtm.pub/other/develop.html

**Comment by yedf2** [comment]
the file is not provided at project root dir, because I want to keep it clean and easy to understand for most users.
