### ISSUE TITLE
Recipe for target 'lint' failed

### ISSUE THREAD

**Issue by wjf222** [dtm-labs/dtm#282]
Golangci-lint detected a code format problem when I followed the steps to run the test case：
https://dtm.pub/other/develop.html 
![image](https://user-images.githubusercontent.com/52238329/166208717-936b9327-51ee-4d1f-9a0e-4dbd46665328.png)

wo should omit type chan branchStatus.
I hope you can assign this issue to me.
I hope to do my first PR.
Thasnks.

branch: main

**Comment by yedf2** [comment]
3q merged
