### ISSUE TITLE
saga模式下 如何获取某个微服务grpc请求的返回结果？

### ISSUE THREAD

**Issue by bbing** [dtm-labs/dtm#289]
saga模式下 如何获取某个微服务grpc请求的返回结果？

**Comment by yedf2** [comment]
saga模式不支持，因为grpc的请求结果通常需要pb文件才能够解析。

对于这种情况，可以有如下的两种解决方案：
1. saga模式下，再写一个接口，让用户可以查询结果
2. 改用TCC模式，将confirm的url设置为空，此时就相当于一个可以获取结果的saga模式

**Comment by bbing** [comment]
感谢
