### ISSUE TITLE
DTM有一次连接try超时之后，之后再重新连接DTM时会一直出现读超时

### ISSUE THREAD

**Issue by JFeng0820** [dtm-labs/dtm#296]
在java例子中，我在barrierTransOutTry打一次断点导致DTM读超时。
放开断点之后。重新再访问api/testTcc，java服务访问DTM时，会一直显示连接超时

应该如何进行处理
![image](https://user-images.githubusercontent.com/51046768/169448685-26912480-5fde-42de-b4f6-cc8b6eb28288.png)

**Comment by yedf2** [comment]
> 在java例子中，我在barrierTransOutTry打一次断点导致DTM读超时。 放开断点之后。重新再访问api/testTcc，java服务访问DTM时，会一直显示连接超时
> 
> 应该如何进行处理 ![image](https://user-images.githubusercontent.com/51046768/169448685-26912480-5fde-42de-b4f6-cc8b6eb28288.png)

你的这个太奇怪了，应该是你的客户端写得有些问题，可以按照例子重新来试一试

**Comment by yedf2** [comment]
问题解决了吗？很久没有更新，将关闭
