### ISSUE TITLE
一个分布式事务中的参与者使用不同的模式？

### ISSUE THREAD

**Issue by wuqinqiang** [dtm-labs/dtm#298]
看了现在的实现，目前开启的一个分布式事务中，所有的参与者模式是统一的。

我在想，有没有一种场景，一个分布式事务中的不同参与者需要使用不同的模式？比如参与者a使用tcc，而参与者b使用的saga?由这种混合模式组成的一个分布式事务？

**Comment by yedf2** [comment]
一般来说，是先有场景，然后去实现功能。另外很多场景，可以用多种模式去解决

**Comment by yedf2** [comment]
https://dtm.pub/practice/workflow.html 这个模式可以支持 @wuqinqiang
