### ISSUE TITLE
有个疑问请问一下,每次开启一个本地xa事务都需要new一个新的*sql.DB吗

### ISSUE THREAD

**Issue by Ysclmml** [dtm-labs/dtm#301]
![image](https://user-images.githubusercontent.com/44059588/172299052-305f7a98-dc75-466e-8140-3f8674139a03.png)
![image](https://user-images.githubusercontent.com/44059588/172299091-ed92f3f2-70d3-455e-919c-cf9fa9a9161a.png)
这个DB可以提前保存吗？可能是我不了解XA事务, 每开启一个事务都需要重新连接数据库，这个不是很耗时吗？

**Comment by yedf2** [comment]
如果多个连接并发，xa commit的连接和xa prepare不是同一个，就不会成功，这个是mysql xa事务不够完善的地方。因此只能够新建连接，prepare之后断开连接

**Comment by Ysclmml** [comment]
> 如果多个连接并发，xa commit的连接和xa prepare不是同一个，就不会成功，这个是mysql xa事务不够完善的地方。因此只能够新建连接，prepare之后断开连接

感谢回答,了解了
