### ISSUE TITLE
windows版  http://localhost:36789 无法显示

### ISSUE THREAD

**Issue by Rockny** [dtm-labs/dtm#308]
![image](https://user-images.githubusercontent.com/15974713/173506970-cff84360-da5b-4d2f-a8a3-90340538854a.png)
配置了redis  和端口 也还是原来默认的
![image](https://user-images.githubusercontent.com/15974713/173507015-2f705226-d125-4bc8-b79a-ea9476349080.png)

#####################################################################
#####################################################################

 Store: # specify which engine to store trans status
#   Driver: 'mysql'
#   Host: 'localhost'
#   User: 'root'
#   Password: ''
#   Port: 3306
#   Db: 'dtm'

#   Driver: 'boltdb' # default store engine

   Driver: 'redis'
   Host: 'localhost'
   User: ''
   Password: ''
   Port: 6379

#   Driver: 'postgres'
#   Host: 'localhost'
#   User: 'postgres'
#   Password: 'mysecretpassword'
#   Port: '5432'

### following config is for only Driver postgres/mysql
#   MaxOpenConns: 500
#   MaxIdleConns: 500
#   ConnMaxLifeTime: 5 # default value is 5 (minutes)

### flollowing config is only for some Driver
#   DataExpire: 604800 # Trans data will expire in 7 days. only for redis/boltdb.
#   FinishedDataExpire: 86400 # finished Trans data will expire in 1 days. only for redis.
#   RedisPrefix: '{a}' # default value is '{a}'. Redis storage prefix. store data to only one slot in cluster

# MicroService: # grpc based microservice config
#   Driver: 'dtm-driver-gozero' # name of the driver to handle register/discover
#   Target: 'etcd://localhost:2379/dtmservice' # register dtm server to this url
#   EndPoint: 'localhost:36790'

# HttpMicroService: # http based microservice config
#   Driver: 'dtm-driver-http' # name of the driver to handle register/discover
#   RegistryType: 'nacos'
#   RegistryAddress: '127.0.0.1:8848,127.0.0.1:8848'
#   RegistryOptions: '{"UserName":"nacos","Password":"nacos","NotLoadCacheAtStart":true}'
#   Target: '{"ServiceName":"dtmService","Enable":true,"Healthy":true,"Weight":10}' # target and options
#   EndPoint: '127.0.0.1:36789'

### the unit of following configurations is second
# TransCronInterval: 3 # the interval to poll unfinished global transaction for every dtm process
# TimeoutToFail: 35 # timeout for XA, TCC to fail. saga's timeout default to infinite, which can be overwritten in saga options
# RetryInterval: 10 # the subtrans branch will be retried after this interval
# RequestTimeout: 3 # the timeout of HTTP/gRPC request in dtm

# LogLevel: 'info'              # default: info. can be debug|info|warn|error
# Log:
#    Outputs: 'stderr'           # default: stderr, split by ",", you can append files to Outputs if need. example:'stderr,/tmp/test.log'
#    RotationEnable: 0           # default: 0
#    RotationConfigJSON: '{}'    # example: '{"maxsize": 100, "maxage": 0, "maxbackups": 0, "localtime": false, "compress": false}'
#
 HttpPort: 36798
 GrpcPort: 36799
# JsonRpcPort: 36791

### advanced options
# UpdateBranchAsyncGoroutineNum: 1 # num of async goroutine to update branch status

**Comment by yedf2** [comment]
需要dtm -c conf.yml，这样才能够使用你的配置文件启动

**Comment by Rockny** [comment]
原来如此，谢谢
![image](https://user-images.githubusercontent.com/15974713/173713732-fad17cdc-e17f-400a-af5a-63cfe006d1fa.png)
![image](https://user-images.githubusercontent.com/15974713/173713764-db69cb75-1841-460c-839a-7ff90a9fb4c2.png)
麻烦再问下这是怎么回事啊？

**Comment by yedf2** [comment]
您可以尝试从github上面下载已经编译好的版本试一下。我这边没有windows，不太好复现问题

**Comment by Rockny** [comment]
https://github.com/dtm-labs/dtm/releases/tag/v1.14.2

**Comment by Rockny** [comment]
就是在这下载的。
![image](https://user-images.githubusercontent.com/15974713/173791225-90809265-37df-4e32-8827-1f89fe864cf0.png)

**Comment by yedf2** [comment]
收到，有空我看看

**Comment by yedf2** [comment]
你试试1.14.4版本，这个版本下，应该正常了

**Comment by yedf2** [comment]
@Rockny 最新版本解决了你的问题吗？

**Comment by Rockny** [comment]
不好意思，現在才回复，最新版已经解决了这个问题。
