### ISSUE TITLE
可否支持多通信协议混用？

### ISSUE THREAD

**Issue by ostatsu** [dtm-labs/dtm#324]
粗略的看了一些示例，配置一组事务时只需指定一个 DTM Server，通过其 URL 区分子事务的通信协议是 HTTP、gRPC 或 JSON-RPC。（补充，用到的 cli 也是不同的）
而在实际使用上，我其实并不太关心与 DTM Server 的通信方式，而是关心每个子事务的通信协议。
我的理想使用方式是配置事务时可以给每个子事务分别指定其通信协议，从而支持多协议混用。

**Comment by xyctruth** [comment]
确实在微服务的场景中，不能保证所有服务都是用相同的 `Protocal`. 应该需要单独指定子事务的 `Protocal`. 

但是如果添加指定子事务的 `Protocal` 的功能，对客户端会有一些比较大的改动。是不是可以通过子事务的 `URL` 来进行一些判断。

现有支持的`Protocal`，http gRPC。 
`http://` 前缀的可以很明确的可以使用 http call 分支接口，
gRPC 的地址上并不会带有协议名称，目前除了http 就是 gRPC。所以对于不带有协议的地址可以直接用gRPC call 分支接口.或者我们可以在要求客户端在使用 gRPC协议时，添加额外的 `grpc://` 的协议名称。

**Comment by xyctruth** [comment]
目前我看到代码应该已经支持通过子事物的 URL 来选择协议。 你可以试下看是否使用正常.
```go
func (t *TransGlobal) getURLResult(uri string, branchID, op string, branchPayload []byte) error {
	if uri == "" { // empty url is success
		return nil
	}
	if t.Protocol == dtmimp.ProtocolHTTP || strings.HasPrefix(uri, "http://") || strings.HasPrefix(uri, "https://") {
		if t.RequestTimeout != 0 {
			dtmimp.RestyClient.SetTimeout(time.Duration(t.RequestTimeout) * time.Second)
		}
		if t.Protocol == "json-rpc" && strings.Contains(uri, "method") {
			return t.getJSONRPCResult(uri, branchID, op, branchPayload)
		}
		return t.getHTTPResult(uri, branchID, op, branchPayload)
	}
	return t.getGrpcResult(uri, branchID, op, branchPayload)
}
```

**Comment by ostatsu** [comment]
> 目前我看到代码应该已经支持通过子事物的 URL 来选择协议。 你可以试下看是否使用正常.
> 
> ```go
> func (t *TransGlobal) getURLResult(uri string, branchID, op string, branchPayload []byte) error {
> 	if uri == "" { // empty url is success
> 		return nil
> 	}
> 	if t.Protocol == dtmimp.ProtocolHTTP || strings.HasPrefix(uri, "http://") || strings.HasPrefix(uri, "https://") {
> 		if t.RequestTimeout != 0 {
> 			dtmimp.RestyClient.SetTimeout(time.Duration(t.RequestTimeout) * time.Second)
> 		}
> 		if t.Protocol == "json-rpc" && strings.Contains(uri, "method") {
> 			return t.getJSONRPCResult(uri, branchID, op, branchPayload)
> 		}
> 		return t.getHTTPResult(uri, branchID, op, branchPayload)
> 	}
> 	return t.getGrpcResult(uri, branchID, op, branchPayload)
> }
> ```

这段代码应该只是用于内部分发的，实际上 `t.Protocol` 的值完全取决于客户端的调用方式。

**Comment by xyctruth** [comment]
```golang
if t.Protocol == dtmimp.ProtocolHTTP || strings.HasPrefix(uri, "http://") || strings.HasPrefix(uri, "https://") {
```

t.Protocol 的值确实是取决于客户端的调用方式, 但这里使用了或者 `||`，也是就是就算客户端调用的不是 ProtocolHTTP，但url前缀是 http:// 也会使用 http 的协议去 call 分支。

**Comment by ostatsu** [comment]
> ```go
> if t.Protocol == dtmimp.ProtocolHTTP || strings.HasPrefix(uri, "http://") || strings.HasPrefix(uri, "https://") {
> ```
> 
> t.Protocol 的值确实是取决于客户端的调用方式, 但这里使用了或者 `||`，也是就是就算客户端调用的不是 ProtocolHTTP，但url前缀是 http:// 也会使用 http 的协议去 call 分支。

哦，我刚开始想成了用 HTTP 协议调 gRPC 子事务，如果反过来的话确实可以，但有一个问题是 gRPC 是要走 protobuf 传输的，子事务 `payload` 为一个 `proto.Message` 对象，这个东西传过去 HTTP Server 解析不了。

**Comment by xyctruth** [comment]
> > ```go
> > if t.Protocol == dtmimp.ProtocolHTTP || strings.HasPrefix(uri, "http://") || strings.HasPrefix(uri, "https://") {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > t.Protocol 的值确实是取决于客户端的调用方式, 但这里使用了或者 `||`，也是就是就算客户端调用的不是 ProtocolHTTP，但url前缀是 http:// 也会使用 http 的协议去 call 分支。
> 
> 哦，我刚开始想成了用 HTTP 协议调 gRPC 子事务，如果反过来的话确实可以，但有一个问题是 gRPC 是要走 protobuf 传输的，子事务 `payload` 为一个 `proto.Message` 对象，这个东西传过去 HTTP Server 解析不了。
> 
> 以 SAGA 为例，gRPC 包 Add 方法为：
> 
> ```go
> func (s *SagaGrpc) Add(action string, compensate string, payload proto.Message) *SagaGrpc {
> ```
> 
> HTTP 包 Add 方法为：
> 
> ```go
> func (s *Saga) Add(action string, compensate string, postData interface{}) *Saga {
> ```

的确是这样的,目前不不支持。

**Comment by yedf2** [comment]
https://dtm.pub/practice/workflow.html
@xyctruth @ostatsu

**Comment by ostatsu** [comment]
> https://dtm.pub/practice/workflow.html @xyctruth @ostatsu

太好了，workflow 模式非常灵活。
