### ISSUE TITLE
不支持自定义响应参数？

### ISSUE THREAD

**Issue by wuqinqiang** [dtm-labs/dtm#325]
看了代码，比如参与事务分支协议是grpc， 最终是通过调用 Invoke函数返回的err值判断分支事务成功与否。
有些老系统,
response 会把err 置nil，把错误信息放入 resp 中。

这种情况是否可以加一层规则，可以由用户自定义一个接口响应错误与否。

**Comment by yedf2** [comment]
对这种功能的支持，预计下周会发布一个版本

**Comment by yedf2** [comment]
https://dtm.pub/practice/workflow.html @wuqinqiang

**Comment by wuqinqiang** [comment]
cool.
