### ISSUE TITLE
"unkown result will be retried" for FAILURE responses

### ISSUE THREAD

**Issue by metaleap** [dtm-labs/dtm#332]
Hi, your docs say that (in REST mode) `"SUCCESS"|"FAILURE"` responses are handled specially, vs. all other errors that will provoke retries.

But sometimes my FAILURE responses cause dtm to log for example:

```
processInner got error: http/grpc result should be specified as in: https://dtm.pub/summary/arch.html#http
unkown result will be retried: { "dtm_result": "FAILURE", "reason": "rejected by my fake busi-rules" } FAILURE
```

(My service's response is the `{ ... }` inside this log quote, the above seems a concat of my resp and then `err.Error()`.)

`unkown result will be retried` sounds unexpected for FAILURE responses wrt docs: I thought `{dtm_result:FAILURE}` would _not_ be retried, what am I missing?

**Comment by yedf2** [comment]
The result of your response should be specified as: https://en.dtm.pub/practice/arch.html#proto

Some operations like "the compensation of Saga", "the confirm/cancel operation of Tcc" should not return failure. See: https://en.dtm.pub/practice/must-succeed.html

**Comment by metaleap** [comment]
That did clear it up for me just nicely, thanks @yedf2 !
