### ISSUE TITLE
事务状态查询接口，不能返回正确的ID

### ISSUE THREAD

**Issue by ruanwenfeng** [dtm-labs/dtm#333]
基于mysql存储 
curl http://127.0.0.1:36789/api/dtmsvr/query?gid=FKLa7jhRPh7mp5zj7Mqsje

![image](https://user-images.githubusercontent.com/27943586/180406294-16cad4cb-80b5-41d8-87b5-99cde568476d.png)
![image](https://user-images.githubusercontent.com/27943586/180407612-0236cacb-50a6-4c57-9cfa-ad2a98844fd3.png)

**Comment by yedf2** [comment]
不同的存储引擎对ID的使用不一样，只有数据库会有值，请不要依赖这个ID
