### ISSUE TITLE
Golang monkey patching library utilized against terms of license

### ISSUE THREAD

**Issue by mattlorimor** [dtm-labs/dtm#351]
The Golang monkey patching library, https://github.com/bouk/monkey, is being utilized directly against [its license](https://github.com/bouk/monkey/blob/master/LICENSE.md):

> Copyright Bouke van der Bijl
> 
> I do not give anyone permissions to use this tool for any purpose. Don't use it.
> 
> I’m not interested in changing this license. Please don’t ask.

It is also archived and not maintained.

**Comment by yedf2** [comment]
it's removed in newest version. thx
