### ISSUE TITLE
saga模式下，怎么做超时控制？

### ISSUE THREAD

**Issue by lrhhhhhh** [dtm-labs/dtm#354]
我了解到 TimeoutToFail 指定了整个全局事务的超时时间，但是我希望事务超时的时间和用户请求的context的deadline保持一致，例如，请求的timeout是2秒，其中包含完成整个saga事务的时间，deadline到后整个saga事务要么完成，要么视为失败。

请问dtm要怎样实现这样的需求？TimeoutToFail的粒度是秒，有没有必要支持毫秒级别？

**Comment by lrhhhhhh** [comment]
补充一下，我当前遇到的问题是客户请求已经超时返回了，但是saga事务仍旧会执行到底，即使超时了但是saga事务仍旧继续执行。但是又不能通过context的deadline来计算TimeoutToFail，因为TimeoutToFail最细的粒度是秒。

**Comment by yedf2** [comment]
saga要支持长事务，所以超时都是dtm服务器那边控制的，不支持客户端这个deadline。
如果你需要客户端控制的话，那么可以用dtm里面的tcc模式，然后把confirm分之设置为空url，这种情况下，你可以灵活控制，如果你的context 超时了，那么就会在函数里面return error，就会回滚了

**Comment by lrhhhhhh** [comment]
ttc模式下怎么做超时控制？我尝试了一下发现仍然做不到，可能是我方法不对。
我的方法是用`dtmgrpc.TccGlobalTransaction2()` 配合`custom()`给`*dtmgrpc.TccGrpc`设置`Context`，这是dtm里推荐的做法吗或者该怎么做？

**Comment by yedf2** [comment]
就是你这么做，有什么问题吗？
