### ISSUE TITLE
tcc 已经返回409，为什么还会无限重试

### ISSUE THREAD

**Issue by xujunfeng** [dtm-labs/dtm#365]

**Comment by xujunfeng** [comment]
如图

**Comment by xujunfeng** [comment]
![微信图片_20221109152745](https://user-images.githubusercontent.com/15045084/200766237-f82cd015-71e4-4367-8fb0-8336a3893990.png)

**Comment by yedf2** [comment]
TCC模式中，只有Try允许返回失败，Confirm和Cancel返回失败是错误的设计

**Comment by xujunfeng** [comment]
好的，感谢
