### ISSUE TITLE
redis数据存储优化

### ISSUE THREAD

**Issue by nearmeng** [dtm-labs/dtm#367]
--对于redis存储引擎，dtm默认会指定前缀，将所有的数据存储到一个slot

这个能否再进行优化一下，让数据存储可以在不同的分片，这样会大大提高事务的并发量

**Comment by yedf2** [comment]
dtm需要定时轮询已经过期的事务，如果保存在十个slot的话，就需要启动十个协程去轮询，因此协程数量会不可控

**Comment by nearmeng** [comment]
这个值可以支持配置吗？

另外，如果想每秒处理的事务数超过1w，有什么好的方法呢？如何集群化？

**Comment by yedf2** [comment]
怎么配呢？你可以给出一个方案来讨论哈
可以部署多组dtm，根据gid的哈希，映射到多个dtm地址

**Comment by nearmeng** [comment]
我看了一下redis部分的实现，有两个问题讨论下：
1） 存储用的RedisPrefix这种方式将数据保存在一个slot，我查了下这种方式是redis cluster约定的方式，如果redis集群化部署采用的其他的方式，比如类似codis之类的，是不是就会有问题
2）目前redis查询一些数据，有使用redis的scan命令，不过很多的redis集群化方式前端proxy是不支持scan命令的

鉴于很多云服务商提供的redis集群化版本都不是redis cluster的方式，是不是dtm的redis存储可以考虑采用自己建立索引的方式来避免scan类的问题，比如在redis中维护一个list或set或zset，其中保存着若干key的集合

**Comment by nearmeng** [comment]
@yedf2 看一下上面这个问题？

**Comment by nearmeng** [comment]
scan这个如果只是用于admin显示，线上是可以不用的，也可以不过功能不一样有点诡异，不过第一个感觉才是大问题，相当于约束了使用的redis集群的集群化方式，使用上可能会有问题；
另外如果把数据分开存储，通过zset对事务id按时间排序会有什么问题，yedf可以详述一下哈

注：对dtm的理解肯定不够到位，yedf不要不耐烦哈，一起推动在使用端可以做的好点

**Comment by yedf2** [comment]
codis会不兼容prefix这种吗？那么它如何解决多个key需要在同一个几点的问题呢？因为lua作为原子操作，必须在一个节点上

数据分在不同的key，可以分不同时间自动过期，在一个key里面，就不行，就得定时任务手动删除，不太好

**Comment by nearmeng** [comment]
不兼容，比如阿里云上的codis是crc32(key)%1024来找到slot，腾讯内的tendis是用的twemproxy也不支持，对于lua脚本分布式下本身就是有使用限制的，不能操作多个节点key

**Comment by yedf2** [comment]
如果这样的话，那就没有手段保证一个事务相关的数据都在一个节点上，就会导致所有事务数据在一个zset或者其他结构里，这种限制下，实现子事务屏障都会很困难，真没办法支持，只能放弃

**Comment by nearmeng** [comment]
阿里云的自建redis集群好像是可以支持hashtag的，这个我回头测试一下

**Comment by yedf2** [comment]
阿里云，腾讯云卖的redis集群，都是支持的，我测过

**Comment by nearmeng** [comment]
好的
