### ISSUE TITLE
Saga state

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#370]
Hi, all! First of all thank you for the excellent library!
I wondered if this framework support persisting the saga state on database to recover from failures.

Thank you

**Comment by yedf2** [comment]
the state of saga is persisted to database/redis/boltdb, which will be recovered automatically.
you can easily test it if you start dtm without any manual config

**Comment by ostafen** [comment]
Okay, thank you. Is there a way to persist it to mySQL?

**Comment by yedf2** [comment]
of course

**Comment by ostafen** [comment]
Is there any example of this? I was looking at a way to implement a saga involving grpc services.
But in these example I couldn't see a way to tell the lib to persist sagas in a mySQL instance.
https://github.com/dtm-labs/dtm-examples/tree/main/examples

**Comment by yedf2** [comment]
https://en.dtm.pub/deploy/base.html
