### ISSUE TITLE
Clarification about workflow.InitGrpc()

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#372]
HI, all. In the examples, I see that a grpc workflow is initialized in the following way:
```golang	
workflow.InitGrpc(busi.DtmGrpcServer, busi.BusiGrpc, s)
```
where s is the grpc server. My question is: why the workflow definition requires the server? What if workflow involves calling multiple services? What if the workflow is defined in a process and the grpc server is in another process?

Is it ok if I  pass the `InitGrpc` function a server which is different from the server being called inside the workflow? For example:
```golang
workflow.InitGrpc(busi.DtmGrpcServer, "", grpc.NewServer())
```
Would the above code work? If so, what is exactly the purpose of the server passed to this call?
Thank you

**Comment by yedf2** [comment]
```// param dtm specify the dtm address
// param clientHost specify the client host for dtm to callback if a workflow timeout
// param grpcServer specify the grpc server
func InitGrpc(grpcDtm string, clientHost string, grpcServer *grpc.Server)
```
If there are errors in workflow.Execute then this workflow will be retried by dtm server. The dtm server will call services in <clientHost::grpcServer::Workflow::Execute> to resume the workflow.

So the 3 params are all required.
