### ISSUE TITLE
Query saga state through dtmcli

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#373]
Hi, everyone. As the title suggests, my question is: is there a way to query a saga state through the dtm client?
The documentation section for `WaitResult` says:  "There are many possible cases, and it is better for the client to query the status of the global transaction through the query interface of dtm."
Can you provide a link to the documentation for the mentioned query API?

**Comment by yedf2** [comment]
currently there is an http API to query the state. I may add the grpc API this weekend

**Comment by ostafen** [comment]
Oh, I see. The http API is also fine for me. Is there any documentation on that?

**Comment by yedf2** [comment]
curl 'localhost:36789/api/dtmsvr/query?gid=xxx'

**Comment by yedf2** [comment]
I will add doc later

**Comment by yedf2** [comment]
Not supported.
It is very hard to notify user for a distributed app.

Because most transactions are finished normally, so polling the result for a specific user is OK.

**Comment by ostafen** [comment]
I see. Thank you :=)
