### ISSUE TITLE
Clarification on workflow.Interceptor

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#374]
Is it safe to use a grpc client for which I have installed a `workflow.Interceptor` also outside a workflow definition?
Or will all calls to the client be intercepted and cached by the interceptor?

**Comment by yedf2** [comment]
it will only intercept request with context of workflow

**Comment by ostafen** [comment]
I'm trying to use custom headers inside a worflow. However, it seems that dtm is not sending headers when using the interceptor.
I'm setting the headers in the following way:
```
workflow.Register(s.Name, func(wf *workflow.Workflow, data []byte) error {
    wf.BranchHeaders = myHeaders
}
```

Any clue?

**Comment by yedf2** [comment]
client v1.16.4 has been released. In this new version, `TransInfo2Ctx` use `AppendToOutgoingContext `

**Comment by ostafen** [comment]
Thank you, but now if I try to extend the workflow context with my headers, then I get:
```
```

**Comment by ostafen** [comment]
The interceptor has currently another problem:
```golang
func Interceptor(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
	logger.Debugf("grpc client calling: %s%s %v", cc.Target(), method, dtmimp.MustMarshalString(req))
	wf := ctx.Value(wfMeta{}).(*Workflow)
```

Basically, if a context without the wfMeta{} key is intercepted, the code will panic, 'cause there is no null check for wf.
I think fix should be:
```golang
wf := ctx.Value(wfMeta{}).(*Workflow)
if wf == nil {
       return nil
}
```

**Comment by yedf2** [comment]
can you make a pr to dtm?

**Comment by yedf2** [comment]
you can pass a ctx to workflow's constructor

**Comment by ostafen** [comment]
`can you make a pr to dtm?`

Of course.

`you can pass a ctx to workflow's constructor`

What do you mean?

**Comment by yedf2** [comment]
> Thank you, but now if I try to extend the workflow context with my headers
> 
> ```go
> wf.Context = metadata.NewOutgoingContext(wf.Context, metadata.Pairs(pairs...))
> ```
> 
> , then I get:
> 
> ```go
> dtmimp.PanicIf(wf.currentActionAdded, fmt.Errorf("one branch can have only on action"))
> ```

This error hint is saying that, you should call NewBranch if you are adding another action

**Comment by yedf2** [comment]
> `you can pass a ctx to workflow's constructor`
> 
> What do you mean?

I am sorry, please ignore it

**Comment by ostafen** [comment]
Oh, I see, so basically every branch should be followed by at most one grpc call, shouldn't it?
Like so:

```golang
wf.NewBranch()...
myOp1
wf.NewBranch()...
myOp2
...
```

While the following is wrong:

```golang
wf.NewBranch()...
myOp1
myOp2
...

**Comment by yedf2** [comment]
yes

**Comment by ostafen** [comment]
Great, I confirm you that this is working. I'm going to submit a fix for the nil check on the Interceptor

**Comment by yedf2** [comment]
I will create a release with this fix tomorrow

**Comment by yedf2** [comment]
released

**Comment by yedf2** [comment]
When you deploy dtm in your production, please help to fill the user list
