### ISSUE TITLE
Customize ErrFailure message

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#376]
Currently, if our application needs to stop the ongoing workflow, it must return either a http/grpc failure error or an ErrFailure.
However, if we are not calling a remote endpoint, the only available alternative is the ErrFailure error.
Is there a way to create custom errors (wich a custom message also) which are treated by dtm as ErrFailure?

**Comment by yedf2** [comment]
You can customize the errors in `GRPCError2DtmError` in workflow's Options.

**Comment by ostafen** [comment]
I guess `GRPCError2DtmError` accepts a grpc error as inpu.
But what if the returned error is not a GRPC error? For example, in the case I'm executing a step which is local to the microservice which define the workflow. (I know that I could wrap the error in a grpc error, but doesn't make too much sense)

**Comment by yedf2** [comment]
If you are doing a local action, you can wrap the error to ErrFailure or ErrOngoing directly.

**Comment by ostafen** [comment]
So for example, like:
```golang
errors.Wrap(myErr, dtmcli.ErrFailure)
```
?

**Comment by yedf2** [comment]
Yes

**Comment by ostafen** [comment]
Oh, great. Just one last question (I don't want to open a new issue for this).
If I have to perform a local step, for example a local sql transaction, is it mandatory to wrap the code inside the `Do()` method?
In the site, it is reported that local steps should be written like:

```golang
wf.Do(func(bb *dtmcli.BranchBarrier) ([]byte, error) {
  return nil, bb.CallWithDB(dbGet(), func(tx *sql.Tx) error {
    return busi.SagaAdjustBalance(tx, busi.TransOutUID, -req.Amount, "")
  })
})
```

In my case, I don't really need to use the barrier, because I'm handling idempodency inside the business logic.
I was wondering, is it still required to put my code inside the `Do()` function?

Thank you

**Comment by yedf2** [comment]
If you put your code in Do, then the progress will be recorded and retries will skip your action.

If you have handle idempodency yourself, and don't mind to call it in next retries, then you can put it out of Do.

My suggestion is you put you code in Do, but ignore the parameter `BranchBarrier`. The Barrier is only a build-in idempodency implementation in case of workflow.

**Comment by ostafen** [comment]
I see. But I guess that `Do()` keeps track of local work through extra sql tables, doesn't it?
In that case, I would rather prefer avoiding to keep the db schema simpler.

**Comment by yedf2** [comment]
`Do` and other remote call keep the progress in dtm server. It does not need local db schema.

**Comment by ostafen** [comment]
I see, in that case it would be the dtm server itself to skip the work. BTW, the important part is that both methods are at least safe, assuming the logic is idempotent.
Thank you for your help!

**Comment by yedf2** [comment]
Yes
