### ISSUE TITLE
Optimize the config-related code.

### ISSUE THREAD

**Issue by wz14** [dtm-labs/dtm#38]
Note that the `common/types.go` file includes two types of logical code: database and config related operations. Is it possible to consider that
- Split `common/types.go` to two files, `common/config.go` and  `common/db.go`.
- Make the `init`  code in `common/types.go` file explicit with the singleton pattern.
- Make hard coded port in `dtmsvr/dtmsvr.go` configured in `config.yaml`.
- Remove `RetryLimit`, which is not used anywhere.

**Comment by yedf2** [comment]
I have think about your suggestion:

- Splitting config code from common/types.go to common/config.go is OK. But it seems not necessary to split out a standalone common/db.go? 
- Init func is already a convenient singleton pattern in Go. There is no essential difference.
- Making port in dtmsvr/dtmsvr.go configured in config.yml and env is a good suggestion.
- Removing RetryLimit is OK.

Do you agree with the above content? If so, can you make a PR? Thank you very much.
