### ISSUE TITLE
Initialization of dtm logger

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#380]
Hi, I'm experimenting an issue with dtm logging initialization. Basically, whenever dtm is imported, the logger is initialized as follows:

```golang
func init() {
     logger.Init(os.GetEnv("LOG_LEVEL")
}
```
Now, the `LOG_LEVEL` env var is already being used by other packages in my case (logrus) to initialize other logging middlewares.
Since the value I'm using is `TRACE`, my code panic inside dtm, because it says that `TRACE` is not a valid value for dtm logger.
Can we fix this piece of code to not panic in the case the `LOG_LEVEL` var contains something not valid?
For example, something like:
```golang
func init() {
     level := os.GetEnv("LOG_LEVEL")
     if !isValidDtmLogLevel(level) {
         level = aDefaultLevelValue
     }
     logger.Init(level)
}
```
Or we could also handle this inside the `logger.Init() ` method. What do you think?

**Comment by yedf2** [comment]
You can make a pr to print a hint to steers and set log level to default when the value is not valid

**Comment by ostafen** [comment]
Ok, I will

**Comment by ostafen** [comment]
Fix: https://github.com/dtm-labs/logger/pull/1

**Comment by ostafen** [comment]
Thank you for merging this. Could you release a new dtm version referencing the last logging commit?

**Comment by yedf2** [comment]
released
