### ISSUE TITLE
未携带header

### ISSUE THREAD

**Issue by zj-kenzhou** [dtm-labs/dtm#383]
在grpc xa 模式下，自定义header 
在第一次执行业务的时候header 是存在的，
后面的 xa commit 或者 rollback 阶段，header 未携带到相关方法

**Comment by yedf2** [comment]
在选项里面设置了branchHeader了吗？

**Comment by yedf2** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/43027375/211306583-7ade7911-380c-4738-b6ce-688b6e79eaf7.png">
我看到da代码里面是做了这方面处理的，你可以看看你的BranchHeaders有没有保存到数据库，然后找找为什么

**Comment by zj-kenzhou** [comment]
![image](https://user-images.githubusercontent.com/37363187/211453026-406c2aae-8600-4137-ad6f-6ecf6783599a.png)

找到问题了，xa 事务grpc 访问 dtm server 的时候，grpc 的参数只设置了gid 和 transtype 没有携带其他参数

**Comment by yedf2** [comment]
帮忙提个pr?

**Comment by zj-kenzhou** [comment]
好的
