### ISSUE TITLE
配置mongodb启动报错

### ISSUE THREAD

**Issue by 191644807** [dtm-labs/dtm#386]
你好，我配置mongodb启动报错
配置如下：
Store:
  Driver: 'mongodb'
  Host: '36.134.194.3'
  User: 'root'
  Password: '11111'
  Port: 27017
  Db: 'dtm'
  directConnection: true

报错如下：

`E:\pro\dtm>dtm.exe -c  ./conf.mongo.yml
{"level":"info","ts":"2023-01-09T09:49:46.696+0800","caller":"entry/main.go:46","msg":"dtm version is: v1.16.5"}
{"level":"info","ts":"2023-01-09T09:49:46.699+0800","caller":"config/config.go:120","msg":"config file: ./conf.mongo.yml loaded config is: \n{\n  \"Store\": {\n    \"Driver\": \"mongodb\",\n    \"Host\": \"36.134.194.3\",\n    \"Port\": 27017,\n    \"User\": \"root\",\n    \"Password\": \"SaReNMFFMJtHidiGbjmbT6EH2KXHTV3h\",\n    \"Db\": \"dtm\",\n    \"Schema\": \"public\",\n    \"MaxOpenConns\": 500,\n    \"MaxIdleConns\": 500,\n    \"ConnMaxLifeTime\": 5,\n    \"DataExpire\": 604800,\n    \"FinishedDataExpire\": 86400,\n    \"RedisPrefix\": \"{a}\"\n  },\n  \"TransCronInterval\": 3,\n  \"TimeoutToFail\": 35,\n  \"RetryInterval\": 10,\n  \"RequestTimeout\": 3,\n  \"HTTPPort\": 36789,\n  \"GrpcPort\": 36790,\n  \"JSONRPCPort\": 36791,\n  \"MicroService\": {\n    \"Driver\": \"default\",\n    \"Target\": \"\",\n    \"EndPoint\": \"\"\n  },\n  \"HTTPMicroService\": {\n    \"Driver\": \"default\",\n    \"RegistryType\": \"\",\n    \"RegistryAddress\": \"\",\n    \"RegistryOptions\": \"{}\",\n    \"Target\": \"\",\n    \"EndPoint\": \"\"\n  },\n  \"UpdateBranchSync\": 0,\n  \"UpdateBranchAsyncGoroutineNum\": 1,\n  \"LogLevel\": \"info\",\n  \"Log\": {\n    \"Outputs\": \"stderr\",\n    \"RotationEnable\": 0,\n    \"RotationConfigJSON\": \"{}\"\n  },\n  \"TimeZoneOffset\": \"\",\n  \"ConfigUpdateInterval\": 3,\n  \"AlertRetryLimit\": 3,\n  \"AlertWebHook\": \"\"\n}"}
{"level":"info","ts":"2023-01-09T09:49:46.699+0800","caller":"maxprocs/maxprocs.go:47","msg":"maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xeb2380]

goroutine 1 [running]:
github.com/dtm-labs/dtm/dtmsvr/storage/registry.GetStore(...)
        /github/workspace/dtmsvr/storage/registry/registry.go:46
github.com/dtm-labs/dtm/dtmsvr/storage/registry.WaitStoreUp()
        /github/workspace/dtmsvr/storage/registry/registry.go:51 +0x40
github.com/dtm-labs/dtm/dtmsvr/entry.Main(0x3774990)
        /github/workspace/dtmsvr/entry/main.go:60 +0x3cd
main.main()
        /github/workspace/main.go:33 +0x25`

请问这是怎么回事，是我的配置哪里chuc出错了吗，我用docker启动也是这种错误

**Comment by yedf2** [comment]
存储引擎目前还不支持mongodb

**Comment by 191644807** [comment]
我看你们文档不是支持mongodb的吗

**Comment by 191644807** [comment]
> 存储引擎目前还不支持mongodb

我看你们文档不是支持mongodb的吗

**Comment by yedf2** [comment]
业务分布式事务中，支持业务方使用mongo，但不支持dtm的数据存储在mongo

**Comment by 191644807** [comment]
感谢您的回答
