### ISSUE TITLE
Start a workflow with a given context

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#396]
Hi, I want to propagate the context.Context object which comes from an http call when starting a new workflow with the `Exec` method, so that I am able to propagate all the values which are set in that context.
Is there a way to do that? Or the `Exec` method should be modified to also accept a `ctx` obect?

**Comment by yedf2** [comment]
You may take a look at the changes make by v1.17.0, it has added `ExecuteCtx` to accept a cox object

**Comment by ostafen** [comment]
Is the ctx object also preserved when a workflow is resubmitted (retried) by the server?

**Comment by goxiaoy** [comment]
ctx can not be serialized . you can set `workflow.BranchHeaders` by `custom` when `workflow.Register2` being called
```golang
custom := func(wf *workflow.Workflow) {
  // set branch header by ctx, such as opentelemetry propagation headers
  wf.BranchHeaders = h.propagateHeader(wf.Context)
}
workflow.Register2(name, handler, custom)
```

see 
https://en.dtm.pub/ref/options.html#transaction-options
https://en.dtm.pub/ref/options.html#branchheaders
