### ISSUE TITLE
admin panel not work 

### ISSUE THREAD

**Issue by lotos2512** [dtm-labs/dtm#399]
admin panel not work , when i try to open http://localhost:36789/PUBLIC-PATH-VARIABLE/ browser get me 304 code and looks like this
![image](https://user-images.githubusercontent.com/7212897/219072680-e01ca2bd-c457-4336-bb41-e8762cde3b2d.png)
![image](https://user-images.githubusercontent.com/7212897/219072786-630758d0-64da-4c84-b664-adf046ffc718.png)

**Comment by mackwan84** [comment]
Same problem either in version 1.16.10 or version 1.17

**Comment by goxiaoy** [comment]
close via https://github.com/dtm-labs/dtm/pull/397 please use v1.17.1
