### ISSUE TITLE
为什么我指定了配置文件，还是无法读取到，数据库还是boltdb

### ISSUE THREAD

**Issue by wuuer** [dtm-labs/dtm#409]
命令:
dtm.exe -c ./config.yml

日志:
invalid log level: , switching to default: INFO
{"level":"info","ts":"2023-03-14T17:30:32.920+0800","caller":"entry/main.go:46","msg":"dtm version is: v1.17.0"}
{"level":"info","ts":"2023-03-14T17:30:32.921+0800","caller":"config/config.go:121","msg":"config file: ./config.yml loaded config is: \n{\n  \"Store\": {\n    \"Driver\": \"boltdb\",\n    \"Host\": \"\",\n    \"Port\": 0,\n    \"User\": \"\",\n    \"Password\": \"\",\n    \"Db\": \"dtm\",\n    \"Schema\": \"public\",\n    \"MaxOpenConns\": 500,\n    \"MaxIdleConns\": 500,\n    \"ConnMaxLifeTime\": 5,\n    \"DataExpire\": 604800,\n    \"FinishedDataExpire\": 86400,\n    \"RedisPrefix\": \"{a}\"\n  },\n  \"TransCronInterval\": 3,\n  \"TimeoutToFail\": 35,\n  \"RetryInterval\": 10,\n  \"RequestTimeout\": 3,\n  \"HTTPPort\": 36789,\n  \"GrpcPort\": 36790,\n  \"JSONRPCPort\": 36791,\n  \"MicroService\": {\n    \"Driver\": \"default\",\n    \"Target\": \"\",\n    \"EndPoint\": \"\"\n  },\n  \"HTTPMicroService\": {\n    \"Driver\": \"default\",\n    \"RegistryType\": \"\",\n    \"RegistryAddress\": \"\",\n    \"RegistryOptions\": \"{}\",\n    \"Target\": \"\",\n    \"EndPoint\": \"\"\n  },\n  \"UpdateBranchSync\": 0,\n  \"UpdateBranchAsyncGoroutineNum\": 1,\n  \"LogLevel\": \"info\",\n  \"Log\": {\n    \"Outputs\": \"stderr\",\n    \"RotationEnable\": 0,\n    \"RotationConfigJSON\": \"{}\"\n  },\n  \"TimeZoneOffset\": \"\",\n  \"ConfigUpdateInterval\": 3,\n  \"AlertRetryLimit\": 3,\n  \"AlertWebHook\": \"\",\n  \"AdminBasePath\": \"\"\n}"}
{"level":"info","ts":"2023-03-14T17:30:32.921+0800","caller":"maxprocs/maxprocs.go:47","msg":"maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined"}
{"level":"info","ts":"2023-03-14T17:30:33.768+0800","caller":"dtmsvr/svr.go:32","msg":"start dtmsvr"}
{"level":"info","ts":"2023-03-14T17:30:33.768+0800","caller":"dtmsvr/svr.go:51","msg":"dtmsvr http listen at: 36789"}
{"level":"info","ts":"2023-03-14T17:30:33.777+0800","caller":"dtmsvr/svr.go:65","msg":"grpc listening at [::]:36790"}
{"level":"info","ts":"2023-03-14T17:30:33.878+0800","caller":"dtmsvr/svr.go:80","msg":"RegisterService: default"}
{"level":"info","ts":"2023-03-14T17:30:33.878+0800","caller":"workspace/main.go:96","msg":"admin is proxied to admin.dtm.pub"}
{"level":"info","ts":"2023-03-14T17:30:33.879+0800","caller":"workspace/main.go:98","msg":"admin is running at: http://localhost:36789"}

配置文件内容:
Store:
Driver: 'mysql'
Host: '127.0.0.1'
User: 'root'
Password: '123'
Port: 3306
Db: 'dtm'

**Comment by yedf2** [comment]
从日志看，读取了config.gi，但估计由于缩进等格式问题导致配置不对
