### ISSUE TITLE
clone run的时候出现的错误

### ISSUE THREAD

**Issue by missbefore** [dtm-labs/dtm#461]
panic: proto: file "auth.proto" is already registered
See https://protobuf.dev/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x2861c60?, 0xc0003351b0?}, {0x2861c60?, 0xc0003351b0})
	/root/go/pkg/mod/google.golang.org/protobuf@v1.31.0/reflect/protoregistry/registry.go:56 +0x1e5
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000012b88, {0x289a360?, 0xc00036aa80?})
	/root/go/pkg/mod/google.golang.org/protobuf@v1.31.0/reflect/protoregistry/registry.go:130 +0x3a6
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x0, 0x0}, {0xc00038aa00, 0x11ee, 0x1500}, 0x2, 0xd, 0x0, 0x0, {0x286a8b0, ...}, ...})
	/root/go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/filedesc/build.go:112 +0x1d6
github.com/golang/protobuf/proto.RegisterFile({0x24a6252, 0xa}, {0x3b0cc00, 0x424, 0x424})
	/root/go/pkg/mod/github.com/golang/protobuf@v1.5.3/proto/registry.go:48 +0x148
github.com/polarismesh/specification/source/go/api/v1/security.init.1()
	/root/go/pkg/mod/github.com/polarismesh/specification@v1.3.2/source/go/api/v1/security/auth.pb.go:1079 +0x34
exit status 2

**Comment by DianWoung** [comment]
~~~
go mod tidy
go build .
./dtm
~~~
试试

**Comment by missbefore** [comment]
> ```
> go mod tidy
> go build .
> ./dtm
> ```
> 
> 试试

编译之后运行，也是错误

**Comment by zhengwjme** [comment]
<img width="1413" alt="image" src="https://github.com/dtm-labs/dtm/assets/9192195/aca28d36-39a2-43cd-9355-0b0ab35133a9">
相同的情况

**Comment by Makonike** [comment]
proto命名冲突了，将这行注释即可
![image](https://github.com/dtm-labs/dtm/assets/75628309/f6a14fd3-5c2b-4dcc-9c58-e98b5c8dc43e)

**Comment by yedf2** [comment]
已经把dtmdriver-polaris的变更回滚，现在没问题了
