### ISSUE TITLE
grpc_saga_passthroughHeaders 中间件设置header后接口中无法获取

### ISSUE THREAD

**Issue by kong9527** [dtm-labs/dtm#462]
如标题，example中，在中间件中设置了kv到ctx中，但是接口TransOutHeaderYes中无法取出

**Comment by yedf2** [comment]
能否给一个可复现的代码链接，以及相关说明，这样方便快速定位问题。当然也可以给更高级的，例如直接给出应当通过，却没有通过的test case

**Comment by kong9527** [comment]
就是官方提供的样例工程，grpc_saga_passthroughHeaders这个使用案例

**Comment by yedf2** [comment]
使用案例哪个地方行为不符合你的预期？能否帮忙一次性把问题说很清晰很细致？

**Comment by yedf2** [comment]
passthroughHeaders发现不实用，你直接用customHeaders就行了

**Comment by kong9527** [comment]
好的，谢谢大佬讲解
