### ISSUE TITLE
tcc模式下，Cancel阶段怎么拿到Try或者Confirm阶段生成的数据

### ISSUE THREAD

**Issue by am6737** [dtm-labs/dtm#486]
当Cancel阶段依赖Try、Confirm阶段生成的数据时（比如数据库自增id），我怎么能优雅的拿到呢，还是我的使用场景有问题，就不应该这么做呢。

**Comment by yedf2** [comment]
普通TCC模式，没办法优雅拿到数据库自增ID，这个一般采用提前生成ID
