### ISSUE TITLE
Can't go mod tidy

### ISSUE THREAD

**Issue by sithu-go** [dtm-labs/dtm#489]
There are many moved packages and renamed packages like
[github.com/mitchellh/osext](url) to [github.com/kardianos/osext](url)

[github.com/googleapis/gnostic](url) to[ github.com/google/gnostic](url)

[github.com/armon/go-metrics](url) to [github.com/hashicorp/go-metrics](url)

**Comment by yedf2** [comment]
can not reproduce your problem. I can run `go mod tidy` successfully.

**Comment by sithu-go** [comment]
Btw, I'm using 1.21.5

can you clean go mod first?
`go clean -modcache`

**Comment by yedf2** [comment]
still can not reproduce your problem.

my following commands succeeded

```
go1.22.2 clean -modcache 
go1.22.2 run main.go 
```

**Comment by sithu-go** [comment]
Try it in docker.
