### ISSUE TITLE
nacos

### ISSUE THREAD

**Issue by zyzgreater** [dtm-labs/dtm#496]

**Comment by zyzgreater** [comment]
naocs 2.x版本注册失败，
![image](https://github.com/dtm-labs/dtm/assets/98529866/8de4c169-9985-400a-a57a-d3f712a561e6)
是不是最新版的dtm不能注册2.x版本的？

**Comment by zyzgreater** [comment]
![image](https://github.com/dtm-labs/dtm/assets/98529866/ddd444fb-8556-4be0-b14a-e09e27a51a27)

**Comment by yedf2** [comment]
@horseLk 有空时帮忙看看这个哈

**Comment by horseLk** [comment]
我看你的endpoint是localhost:36789，请问nacos和dtmService是否在一台机器上呢？如果不在的话需要将localhost 换成可访问的IP

**Comment by zyzgreater** [comment]
这个endpoint这个确认了，是一样的错误，dtm试了1.18.0与1.17.8，nacos是2.3.1的，配置的话就是
`MicroService:
  Driver: 'dtm-driver-springcloud'
  Target: '{"Addr":"xxx:8848","Type":"nacos", "InstanceConfig":{"ServiceName":"dtmService","Enable":true,"Healthy":true,"Weight":10},"ClientConfig":{"NamespaceId":"c3dc917d-906a-429d-90a9-85012b41014e","UserName":"nacos","Password":"nacos","NotLoadCacheAtStart":true}}'
  EndPoint: 'xxx:36789'`

**Comment by horseLk** [comment]
@zyzgreater 你好，看了一下相关的配置是没有问题的，看图片相关的服务也已经注册上去了，只是服务处于不健康的状态。请先检查一下：nacos所在服务器是否能链接dtmService。

**Comment by zyzgreater** [comment]
是防火墙的问题，现在能正常注册了但是dtm服务停止后，nacos服务列表中dtm不会清空，其他的服务停止后nacos上就会消失，是dtm服务需要配置什么参数吗

**Comment by horseLk** [comment]
dtm只会注册服务 不会删除服务哈
