### ISSUE TITLE
dtmcli-java的api问题

### ISSUE THREAD

**Issue by zyzgreater** [dtm-labs/dtm#497]
![image](https://github.com/dtm-labs/dtm/assets/98529866/758cf22b-b8a1-460f-b2b0-583605053ba2)
![image](https://github.com/dtm-labs/dtm/assets/98529866/601233d9-9b07-4188-972e-65df673cd3d7)
![image](https://github.com/dtm-labs/dtm/assets/98529866/2208d3ae-466b-42e3-bd4d-c62cdb61df40)
![image](https://github.com/dtm-labs/dtm/assets/98529866/1c499524-3ab3-4382-b197-fd660b48e37c)
1.这是官网dtm中dtmcli-java的例子，其中图一调用tccBarrierHttp这个接口，开始tcc事务；2.图二tcc.callBranch 通过这个方法进行，body与try、confirm、cancel注册，图三

**Comment by zyzgreater** [comment]
上接：3.图三是tcc.callBranch这个方法的源码，进行dtm注册，注册的body在confirm与cancel是一样的数据；4.图四是try与cancel的数据库执行语句方法，调用的是同一个，这个是补偿逻辑吗，为啥try与cancel的body和sql一模一样

**Comment by horseLk** [comment]
这个case看起来确实有点问题，这个cancel应该再前面加一个负号

**Comment by zyzgreater** [comment]
对应java的xa模式会支持吗

**Comment by horseLk** [comment]
暂时可能没有时间支持，如果社区有其他的同学可以提供PR
