### ISSUE TITLE
子事务注册接口支持传入header

### ISSUE THREAD

**Issue by goldenages1989** [dtm-labs/dtm#87]
调用正向和补偿操作的接口都需要鉴权，鉴权是通过读取header头里面的鉴权token来实现的
是否可以支持在注册的时候把鉴权信息放在header头带上呢。

**Comment by yedf2** [comment]
能帮忙把期望的输入输出说明清楚吗？还有是http还是grpc？

**Comment by goldenages1989** [comment]
是http模式
期望在注册子事务的时候除了body之外，可以再传入header信息，比如registerTccBranch的参数加上header参数。
然后dtm调用正向和补偿操作的时候，除了把body传给api外，再把header头也透传过去，因为api中会用到header头中的信息来进行鉴权

**Comment by yedf2** [comment]
与你讨论一下功能点设计：
我计划的做法是在事务上面，有个SetHeader函数，允许用户设置header信息。
为什么这么设计：
- 新设计不会更改现有的接口，只是新加一个接口。
- 虽然在每个子事务上面设置header最灵活，但实际的项目中，在事务这个粒度设置header更符合大多数的应用场景

请帮忙反馈您的意见

**Comment by goldenages1989** [comment]
> 与你讨论一下功能点设计： 我计划的做法是在事务上面，有个SetHeader函数，允许用户设置header信息。 为什么这么设计：
> 
> * 新设计不会更改现有的接口，只是新加一个接口。
> * 虽然在每个子事务上面设置header最灵活，但实际的项目中，在事务这个粒度设置header更符合大多数的应用场景
> 
> 请帮忙反馈您的意见

嗯嗯，到事务粒度即可。新加接口更合理

**Comment by yedf2** [comment]
预计春节前的某个版本能够加上这个特性

**Comment by goldenages1989** [comment]
> 预计春节前的某个版本能够加上这个特性

辛苦啦，我们已经在接入了，现在卡在这一步了，期待能早些加入该特性

**Comment by yedf2** [comment]
特性已添加
