### ISSUE TITLE
添加测试用例，覆盖截图中的红色代码

### ISSUE THREAD

**Issue by yedf2** [dtm-labs/dtm#97]
![image](https://user-images.githubusercontent.com/43027375/146646373-f65398f2-aa49-44e9-af55-43b2258be57e.png)

**Comment by li-xiao-shuang** [comment]
> ![image](https://user-images.githubusercontent.com/43027375/146646373-f65398f2-aa49-44e9-af55-43b2258be57e.png)

这是哪个类中的
